### ISSUE TITLE
Stroke width

### ISSUE THREAD

**Issue by fmarotta** [simonpenel/light_phylogeny#1]
Hello, thanks for sharing this! Would it be possible to make the stroke width for the 'pipe' and 'path' trees a user-defined option? I think then it would also make sense to add options for the size of the squares and crosses for duplications and losses.

**Comment by simonpenel** [comment]
Hello, thanks this suggestion! I will add this to the options and config file ,it should not take long, 
Best,

**Comment by simonpenel** [comment]
Hello, 
I just added 3 options so it is possible to specify the thickness of the stroke in gene trees, the thickness of the stroke in species trees, and the size of the symbols:

gthickness, sthickness and squaresize

https://docs.rs/light_phylogeny/latest/light_phylogeny/struct.Options.html

In the thirdkind v3.2.0, these options are handled with:

    -k size: size of the circles, crosses, squares, etc.
    -z thickness: thickness of the gene tree
    -Z thickness: thickness of the species tree

This is not perfect because the width of the species tree branches does not take into account the stroke thickness of the genes nor the size of symbols, so values ​​that are too large should be avoided.

**Comment by fmarotta** [comment]
That's great for me, thanks!
